# Generated by Django 4.2.4 on 2023-09-16 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sustain',
            new_name='Company',
        ),
        migrations.CreateModel(
            name='Sustainability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ESG', models.IntegerField()),
                ('carbon', models.IntegerField()),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='susSymbol', to='scone.company')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockSymbol', to='scone.company')),
            ],
        ),
    ]
