# Generated by Django 4.2.4 on 2023-09-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scone', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyy',
            name='id',
        ),
        migrations.AddField(
            model_name='companyy',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='companyy',
            name='symbol',
            field=models.CharField(default=0, max_length=5, primary_key=True, serialize=False),
        ),
    ]
