# Generated by Django 4.2.4 on 2023-09-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scone', '0002_rename_sustain_company_sustainability_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sustainability',
            name='symbol',
        ),
        migrations.AddField(
            model_name='company',
            name='CT',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ESG',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='EV',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='FS',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='NH',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Sustainability',
        ),
    ]
