# Generated by Django 4.2.4 on 2023-09-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scone', '0004_remove_companyy_ct_remove_companyy_esg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecovitality',
            name='company',
        ),
        migrations.RemoveField(
            model_name='esg',
            name='company',
        ),
        migrations.RemoveField(
            model_name='feldscore',
            name='company',
        ),
        migrations.RemoveField(
            model_name='natureharmony',
            name='company',
        ),
        migrations.AddField(
            model_name='companyy',
            name='CT',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyy',
            name='ESG',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyy',
            name='EV',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyy',
            name='FS',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyy',
            name='NH',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='CompanyTurnover',
        ),
        migrations.DeleteModel(
            name='EcoVitality',
        ),
        migrations.DeleteModel(
            name='ESG',
        ),
        migrations.DeleteModel(
            name='FeldScore',
        ),
        migrations.DeleteModel(
            name='NatureHarmony',
        ),
    ]
